### ISSUE TITLE
Tested PHP versions

### ISSUE THREAD

**Issue by Sara51D** [51Degrees/device-detection-php#10]
This issue has been moved from another GH issue. A customer has raised the following:

'In your updated CI file you only test against PHP 8.0 - 8.2
Does it mean this package only targets PHP 8+ ? Or PHP 7 and PHP 5.5-5.6 is still needed?

Generally speaking, the more recent PHP version is used the shorter, more stable and reliable code can be written. Even if you drop PHP 5.6 here (which is barely used these days - see https://packagist.org/php-statistics - less than 0.5% worldwide), a null coalescing operator can be used to write, for example:
$this->minify = $settings["minify"] ?? true;
instead of
$this->minify = isset($settings["minify"]) ? $settings["minify"] : true;

Also, this project uses a lot of what's called dynamically added class properties, which was okay in PHP 4, then considered an anti-pattern at the time of PHP 5, now it generates warnings in PHP 8.2 (affects the performance) and will be removed in PHP 8.3. The lack of warnings in the older versions of PHP hid the fact that this:

$filter = new EvidenceKeyFilter();

$filter->filterEvidenceKey = function ($key) {
doesn't work, so you have bugs in JavascriptBuilder.php and SequenceElement.php which you are probably unaware of.'

**Comment by Sara51D** [comment]
Our current policy is to test all the LTS versions of PHP ( see [here](https://en.wikipedia.org/wiki/PHP#Release_history but we're looking to review it in light of customer feedback, so your opinion is valued. Thank you.

**Comment by AlexanderKarpanProdege** [comment]
I would suggest to base your next major release on php 7.4 - it's no longer maintained but still being actively used. And test it for php 7.4, 8.0, 8.1 and 8.2.

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege , thank you for your inputs, we have now started testing for version 7.4 onwards.
