### ISSUE TITLE
Broken symlink in 'tests/51degrees.csv'

### ISSUE THREAD

**Issue by AlexanderKarpanProdege** [51Degrees/device-detection-php#12]
This is probably an issue specific to our setup only, but maybe you'll take this into an account in your future updates.

We have a CI/CD pipeline which prepares the image of our application (checks out the latest code, runs 'composer install', copies the configuration etc.). The last step is zipping the result, which fails because of the broken symlink in 'tests/51degrees.csv'

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege Thank you for bringing this up. We have resolved this issue, could you please let us know if this is working fine for you now. Thank you.

**Comment by AlexanderKarpanProdege** [comment]
Hi @Sara51D 
The recent commit has fixed it - thank you!
Can you please make the next release for this package?

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege, This has now been released.

**Comment by AlexanderKarpanProdege** [comment]
Thank you!
