### ISSUE TITLE
Error building Pipeline inside Laravel project

### ISSUE THREAD

**Issue by Federico-22** [51Degrees/device-detection-php#2]
Creating a Pipeline inside a controller of a laravel project, throw this exception:

`required(vendor/autoload.php): Failed to open stream: No such file or directory`.

The problem is that the class `HardwareProfileCloud.php` requires the file `vendor/autoload.php`, but if the pipeline is built from a folder that is not the project root it causes the exception.

The solution can be avoid to require the file `vendor/autoload.php` inside this class, or make dynamic the path of the file itself.

**Comment by jwrosewell** [comment]
We will need to investigate changes to the way the solution works with Composer along the lines suggested by @Federico-22. We'll seek to schedule this in the coming months.

In the meantime are you able to remove the reference for your specific use case? Or make a pull request with the suggested modification?

**Comment by Federico-22** [comment]
Thanks in advance!

Yes, for now I bypassed the problem overriding the file `HardwareProfileCloud.php` and commenting the line where is required the autoload file.

**Comment by justadreamer** [comment]
After migrating to using PSR-4 Autoloader, this should be addressed, please let us know if not by reopening this issue.
