### ISSUE TITLE
Issues Setting up/Running Web Examples

### ISSUE THREAD

**Issue by Jamesr51d** [51Degrees/device-detection-php#55]
# Environment
Windows(not WSL) - PHP 8.2

# Issues List 
 - [x] In file 'gettingStartedConsole.php, line `if (basename(__FILE__) == basename($_SERVER['SCRIPT_FILENAME'])) {` would be improved by doing a case insensitive comparison using strtolower() function. 
 - [x] This command listed in the README `php -S localhost:3000 cloud/gettingstarted.php` should be changed to '/gettingstartedConsole.php' as there is no 'gettingstarted.php'
 - [ ] The below error was encountered when running the gettingStartedWeb.php example. curl_exec() function is returning false instead of a string. I suspect its not reaching this line `curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);` as CURLOPT_RETURNTRANSFER makes the function return a string instead on success instead of a bool. 
 ```
Fatal error: Uncaught TypeError: substr(): Argument #1 ($string) must be of type string, 
bool given in D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.cloudrequestengine\src\HttpClient.php:86 Stack trace: #0 D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.cloudrequestengine\src\HttpClient.php(86): substr(false, 0, 0) #1 D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.cloudrequestengine\src\CloudRequestEngine.php(296): fiftyone\pipeline\cloudrequestengine\HttpClient->makeCloudRequest
('GET', 'https://cloud.5...', NULL, '51Degrees.examp...') #2 D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.cloudrequestengine\src\CloudRequestEngine.php(119): fiftyone\pipeline\cloudrequestengine\CloudRequestEngine->getEngineProperties() #3 D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.engines\src\Engine.php(107): fiftyone\pipeline\cloudrequestengine\CloudRequestEngine->processInternal
(Object(fiftyone\pipeline\core\FlowData)) #4 D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.core\src\FlowData.php(88): fiftyone\pipeline\engines\Engine->process(Object(fiftyone\pipeline\core\FlowData)) #5 D:\PHP-CLOUD\examples\cloud\classes\GettingStartedConsole.php(121): fiftyone\pipeline\core\FlowData->process() #6 D:\PHP-CLOUD\examples\cloud\classes\GettingStartedConsole.php(76):
 fiftyone\pipeline\devicedetection\examples\cloud\classes\GettingStartedConsole->analyseEvidence(Array, Object(fiftyone\pipeline\core\Pipeline), Array) #7 D:\PHP-CLOUD\examples\cloud\gettingStartedConsole.php(90): fiftyone\pipeline\devicedetection\examples\cloud\classes\GettingStartedConsole->run(Array, Object(fiftyone\pipeline\core\Logger), Array) #8 D:\PHP-CLOUD\examples\cloud\gettingStartedConsole.php(93)
  main(NULL) #9 {main} thrown in D:\PHP-CLOUD\vendor\51degrees\fiftyone.pipeline.cloudrequestengine\src\HttpClient.php on line 86
```
- [x] The README should specify that the resource key should be set as an environment variable. Adding a template command such as `set resource_key=RESOURCE_KEY_HERE` would be informative.

**Comment by justadreamer** [comment]
Our CI does not test PHP repos on Windows - this is because it is a very rare environment choice for PHP development, I suggest we specify this in the docs that Windows is not officially supported for PHP API, but users may file a feature request if they need this.

**Comment by justadreamer** [comment]
addressed the 3 issues in the PR, suggest the error seems to be in the category of won't fix as it is not reproduced on linux and macos - added a warning in README that Windows environment is not explicitly supported

**Comment by Jamesr51d** [comment]
The changes look good to me!
